---
- name: "Installing & configuring mariadb-server"
  hosts: amazon
  become: true
  vars_files:
    - apache.vars
  tasks:


    - name: "Apache - package Installation"
      yum:
        name: httpd
        state: present

    - name: "Apache - Crating VirtualHost /etc/httpd/conf.d/default.conf"
      template:
        src: virualhost.conf.tmpl
        dest: /etc/httpd/conf.d/default.conf
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "Apache - Creating DocumentRoot /var/www/html/{{ domain_name }}"
      file:
        path: "/var/www/html/{{ domain_name }}"
        state: directory
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"


    - name: "Apache - Creating test.html & test.php"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ domain_name }}"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"
      with_items:
        - test.php
        - test.html

    - name: "Apache - Installing php support"
      shell: amazon-linux-extras install php7.4 -y


    - name: "Apache - Restarting/Enabling php-fpm"
      service:
        name: php-fpm
        state: restarted
        enabled: true


    - name: "Apache - Restarting/Enabling Service"
      service:
        name: httpd
        state: restarted
        enabled: true

